-- require("plugins-setup")
require("lazy-setup")
require("core.options")
require("core.keymaps")
require("core.colorscheme")
require("plugins.lsp.lspconfig")
require("plugins.lsp.mason")
require("plugins.lsp.null-ls")
require("plugins.ansible")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.which-key")
